import { type CommandSpec, GROUP_DESCRIPTIONS, longFlag, SPECS } from "../surface/spec.ts";

/**
 * zsh completion generated from the CLI spec (plan §12 F9), so it can never drift from the
 * commands. Install: `orctl completion zsh > "${fpath[1]}/_orctl"` and restart the shell.
 */
const GLOBAL = [
  "-p",
  "--profile",
  "--json",
  "--csv",
  "--columns",
  "--no-color",
  "--quiet",
  "--debug",
  "--timeout",
  "--yes",
  "--config",
  "--refresh",
  "--offline",
  "--help",
];

const q = (s: string) => `'${s.replace(/'/g, "'\\''")}'`;

interface Node {
  children: Map<string, string>;
  flags: string[];
}

function tree(specs: readonly CommandSpec[]): Map<string, Node> {
  const nodes = new Map<string, Node>();
  const node = (key: string) => {
    let n = nodes.get(key);
    if (!n) {
      n = { children: new Map(), flags: [] };
      nodes.set(key, n);
    }
    return n;
  };
  node("");
  for (const spec of specs) {
    for (const path of [spec.path, ...(spec.aliases ?? [])]) {
      path.forEach((word, i) => {
        const parent = path.slice(0, i).join(" ");
        const isLeaf = i === path.length - 1;
        const description = isLeaf
          ? spec.description
          : (GROUP_DESCRIPTIONS[word] ?? node(parent).children.get(word) ?? `${word} commands`);
        node(parent).children.set(word, description);
        if (isLeaf) node(path.join(" ")).flags = spec.flags.map((f) => longFlag(f.flags));
        else node(path.slice(0, i + 1).join(" "));
      });
    }
  }
  node("").children.set("tui", "Open the interactive terminal UI");
  node("").children.set("completion", "Print shell completion (zsh)");
  return nodes;
}

export function zshCompletion(specs: readonly CommandSpec[] = SPECS): string {
  const nodes = tree(specs);
  const children: string[] = [];
  const descriptions: string[] = [];
  const flags: string[] = [];
  for (const [key, n] of [...nodes.entries()].sort(([a], [b]) => a.localeCompare(b))) {
    if (n.children.size) children.push(`  ${q(key)} ${q([...n.children.keys()].join(" "))}`);
    for (const [child, desc] of n.children) descriptions.push(`  ${q(`${key}|${child}`)} ${q(desc)}`);
    if (n.flags.length) flags.push(`  ${q(key)} ${q(n.flags.join(" "))}`);
  }
  return `#compdef orctl
# Generated by \`orctl completion zsh\` from the command spec.

typeset -gA _orctl_children=(
${children.join("\n")}
)
typeset -gA _orctl_desc=(
${descriptions.join("\n")}
)
typeset -gA _orctl_flags=(
${flags.join("\n")}
)

_orctl() {
  local node="" w
  local -a args=(\${words[2,CURRENT-1]})
  local i=1
  while (( i <= \${#args} )); do
    w=\${args[i]}
    if [[ $w == -p || $w == --profile || $w == --columns || $w == --timeout || $w == --config ]]; then
      (( i += 2 )); continue
    fi
    if [[ $w != -* && " \${_orctl_children[$node]} " == *" $w "* ]]; then
      node="\${node:+$node }$w"
    fi
    (( i++ ))
  done
  case \${words[CURRENT-1]} in
    -p|--profile)
      local -a profiles=(\${(f)"$(orctl profile list --csv --columns name 2>/dev/null | tail -n +2)"})
      compadd -a profiles; return ;;
    --config) _files; return ;;
  esac
  if [[ $PREFIX == -* ]]; then
    local -a opts=(\${=_orctl_flags[$node]} ${GLOBAL.join(" ")})
    compadd -a opts
    return
  fi
  if [[ -n \${_orctl_children[$node]} ]]; then
    local -a subs=()
    local c
    for c in \${=_orctl_children[$node]}; do subs+=("$c:\${_orctl_desc[$node|$c]}"); done
    _describe -t commands 'orctl command' subs
  fi
}

_orctl "$@"
`;
}
